version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    reviewers:
      - "benmezger"
    assignees:
      - "benmezger"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "workflow"
    reviewers:
      - "benmezger"
    assignees:
      - "benmezger"
